from .InferCifarResNet import InferCifarResNet
from .InferCifarResNet_depth import InferDepthCifarResNet
from .InferCifarResNet_width import InferWidthCifarResNet
from .InferImagenetResNet import InferImagenetResNet
from .InferMobileNetV2 import InferMobileNetV2
